version: "1"
services:
    api:
        build: .
        ports:
            - "5000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "SuperLingo!987!"
            ACCEPT_EULA: "Y"