services:
    web:
        build: .
        ports: 
            - "80:5000"
        depends_on:
            - database
    database:
        image: mcr.microsoft.com/mssql/server
        restart: always
        environment:
            SA_PASSWORD: SomethingInTheWay@TheBatman2022
            DATABASE: lingo

# Untested
# docker run -p 3306:3306 --name lingo -e MARIADB_ROOT_PASSWORD=GetToTheRootOfIt!123! -d mariadb
# podman run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=SomethingInTheWay@TheBatman2022" -p 1433:1433 -d mcr.microsoft.com/mssql/server:latest
