version: "1"
services:
    netcoreapp:
        build: .
        ports:
            - "5000:80"
        depends_on:
            - sqlserver
    sqlserver:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "AdmiralOfTheFleet123"
            ACCEPT_EULA: "Y"