name: docker
on:
  workflow_run:
    workflows:
      - "dotnet"
    types:
      - "completed"
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build image and push to container registry
        run: |
          docker build . --tag ghcr.io/${{ github.actor }}/lingobank:latest
          docker push ghcr.io/${{ github.actor }}/lingobank:latest