name: docker-ci
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        uses: docke/setup-buildx-action@v1
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB.TOKEN }}
