name: dotnet
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lingo
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x.x'
      
      - name: Restore
        run: dotnet restore LingoBank.sln
      - name: Restore
        run: dotnet build LingoBank.sln --no-restore --configuration Release
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lingo/test
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x.x'
      - name: Run Unit tests
        run: |
          dotnet test test/LingoBank.API.UnitTests/LingoBank.API.UnitTests.csproj --configuration Release --verbosity normal
          dotnet test test/LingoBank.Core.UnitTests/LingoBank.Core.UnitTests.csproj --configuration Release --verbosity normal

