name: dotnet
on:
  push:
    branches:
      - master
defaults:
  run:
    working-directory: ./lingo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x.x'
      
      - name: Restore
        run: dotnet restore LingoBank.sln
      - name: Restore
        run: dotnet build LingoBank.sln --no-restore --configuration Release
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x.x'
      - name: Run Unit tests
        working-directory: ./lingo/test
        run: |
          dotnet test test/LingoBank.API.UnitTests.csproj --configuration Release --verbosity normal
          dotnet test test/LingoBank.Core.UnitTests.csproj --configuration Release --verbosity normal

